title: Avik Dwivedi
email: avikdpanda@gmail.com
description: >-
  A simple site built with Jekyll and GitHub Pages.
baseurl: "/my-jekyll-site" # your repo name, important if not at root
url: "https://vikuser99.github.io" # your GitHub Pages URL

theme: minima

plugins:
  - jekyll-feed

header_pages:
  - about.md
  - basketball.md
  - hindustani-music.md
  - martial-arts.md

